/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.69
 * Generated at: 2023-01-04 00:38:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.net.URLEncoder;
import java.net.URL;
import java.net.HttpURLConnection;
import java.io.BufferedReader;
import java.io.InputStreamReader;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1671504870577L));
    _jspx_dependants.put("jar:file:/C:/Users/ezen/Desktop/project3-main/project3-main/.metadata/.plugins/org.eclipse.wst.server.core/tmp1/wtpwebapps/book/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.net.HttpURLConnection");
    _jspx_imports_classes.add("java.net.URLEncoder");
    _jspx_imports_classes.add("java.net.URL");
    _jspx_imports_classes.add("java.io.BufferedReader");
    _jspx_imports_classes.add("java.io.InputStreamReader");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("	<title>Home</title>\n");
      out.write("	<style type=\"text/css\">\n");
      out.write("	.best{\n");
      out.write("	display:flex;\n");
      out.write("	margin-top:50px;\n");
      out.write("	}\n");
      out.write("	.bestseller{\n");
      out.write("		width:300px;\n");
      out.write("		 height:300px;\n");
      out.write("            margin: 10px;\n");
      out.write("	}\n");
      out.write("	</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<div>\n");
      out.write("	");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\n');
      out.write('	');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("	<ul><a href=\"#\">고객센터</a></ul>\n");
      out.write("	<ul><a href=\"#\">장바구니</a></ul>\n");
      out.write("</div>\n");
      out.write("<div>\n");
      out.write("	<a href=\"#\">로고자리</a>\n");
      out.write("	<a>검색창</a>\n");
      out.write("</div>\n");
      out.write("<div> 슬라이드</div>\n");
      out.write("<div class=\"best\">\n");
      out.write("	베스트 셀러\n");
      out.write("	<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"best\">\n");
      out.write("	베스트 셀러\n");
      out.write("	<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");
      out.write("<div class=\"best\">\n");
      out.write("	베스트 셀러\n");
      out.write("	<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("		<div class=\"bestseller\">\n");
      out.write("		<img src=\"https://shopping-phinf.pstatic.net/main_3551147/35511477623.20221101095929.jpg?type=w300\">\n");
      out.write("	<div>\n");
      out.write("		만일 내가 인생을 다시 산다면(10만 부 기념 스페셜 에디션)\n");
      out.write("	</div>\n");
      out.write("	</div>\n");
      out.write("</div>\n");

    String clientId = "4NMOgJ2RQBlsecZK4ye2";//애플리케이션 클라이언트 아이디값";
    String clientSecret = "kW4Wu3QWAp";//애플리케이션 클라이언트 시크릿값";
    String code = request.getParameter("code");
    String state = request.getParameter("state");
    String redirectURI = URLEncoder.encode("http://localhost:8089/", "UTF-8");
    String apiURL = "https://nid.naver.com/oauth2.0/token?grant_type=authorization_code"
        + "&client_id=" + clientId
        + "&client_secret=" + clientSecret
        + "&redirect_uri=" + redirectURI
        + "&code=" + code
        + "&state=" + state;
    String accessToken = "http://localhost:8089/mem/callback";
    String refresh_token = "";
    try {
      URL url = new URL(apiURL);
      HttpURLConnection con = (HttpURLConnection)url.openConnection();
      con.setRequestMethod("GET");
      int responseCode = con.getResponseCode();
      BufferedReader br;
      if (responseCode == 200) { // 정상 호출
        br = new BufferedReader(new InputStreamReader(con.getInputStream()));
      } else {  // 에러 발생
        br = new BufferedReader(new InputStreamReader(con.getErrorStream()));
      }
      String inputLine;
      StringBuilder res = new StringBuilder();
      while ((inputLine = br.readLine()) != null) {
        res.append(inputLine);
      }
      br.close();
      if (responseCode == 200) {
        out.println(res.toString());
      }
    } catch (Exception e) {
      // Exception 로깅
    }
  
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(28,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_id ==null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	<ul><a href=\"/mem/loginPage\">로그인</a></ul>\n");
          out.write("	<ul><a href=\"/mem/joinPage\">회원가입</a></ul>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(32,1) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_id !=null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	<ul><a href=\"/mem/logOut\">로그아웃</a></ul>\n");
          out.write("	<ul><a href=\"/mem/mypage\">마이페이지 ");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ses.mem_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a></ul>\n");
          out.write("	");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
